include gemBS_config.mk

TARGETS = subdirs
ifeq ($(INSTALL_TEXLIVE),yes)
  TARGETS += texlive
endif

GEMBS_INSTALL_ROOT ?= /usr/local/lib/gemBS
bin_dir = $(GEMBS_INSTALL_ROOT)/bin
etc_dir = $(GEMBS_INSTALL_ROOT)/etc
css_dir = $(etc_dir)/css
cfg_dir = $(etc_dir)/config_scripts

SUBDIRS = rust c_tools
INSTALLDIRS = $(GEMBS_INSTALL_ROOT) $(bin_dir) $(etc_dir) $(css_dir) $(cfg_dir)

.PHONY: subdirs $(SUBDIRS) installdirs all clean distclean texlive

all: $(TARGETS)

install: all installdirs
	cp rust/bin/* $(bin_dir)
	cp c_tools/bin/* $(bin_dir)
	cp c_tools/bcftools/bcftools $(bin_dir)
	cp c_tools/samtools/samtools $(bin_dir)
	cp c_tools/htslib/bgzip $(bin_dir)
#	cp c_tools/bs_call/bin/* $(bin_dir)
	cp c_tools/gem3-mapper/bin/gem-mapper $(bin_dir)
	cp c_tools/gem3-mapper/bin/gem-indexer $(bin_dir)
	cp etc/css/style.css $(css_dir)
	cp etc/config_scripts/*.conf $(cfg_dir)

texlive: .texlive

clean:
	$(MAKE) -C rust clean
	$(MAKE) -C c_tools clean

distclean:
	$(MAKE) -C rust distclean
	$(MAKE) -C c_tools distclean
	rm -f .texlive texlive/gemBS_texlive.profile texlive/texlive_install.sh
	
subdirs: $(SUBDIRS)

$(SUBDIRS): 
	$(MAKE) -C $@

installdirs: $(INSTALLDIRS)

$(INSTALLDIRS):
	mkdir -p $@

$(bin_dir): $(GEMBS_INSTALL_ROOT)
$(etc_dir): $(GEMBS_INSTALL_ROOT)
$(css_dir): $(css_dir)
$(cfg_dir): $(etc_dir)

texlive/gemBS_texlive.profile: texlive/gemBS_texlive.profile.in gemBS_config.mk
	sed 's+@GEMBS_INSTALL_ROOT+$(GEMBS_INSTALL_ROOT)+g;s+@INSTALL_PREFIX+$(INSTALL_PREFIX)+g' $< > $@

texlive/texlive_install.sh: texlive/texlive_install.sh.in gemBS_config.mk
	sed 's+@GEMBS_INSTALL_ROOT+$(GEMBS_INSTALL_ROOT)+g' $< > $@

.texlive: texlive/gemBS_texlive.profile texlive/texlive_install.sh
	cd texlive && sh texlive_install.sh && touch .texlive
