include gemBS_config.mk

TARGETS = subdirs
GEMBS_INSTALL_ROOT ?= /usr/local/lib/gemBS
TMP_ROOT=$(abspath c_tools/tmp_root)

export GEMBS_INSTALL_ROOT TMP_ROOT

ifeq ($(INSTALL_TEXLIVE),yes)
  TARGETS += texlive
endif

bin_dir = $(GEMBS_INSTALL_ROOT)/bin
etc_dir = $(GEMBS_INSTALL_ROOT)/etc
lib_dir = $(GEMBS_INSTALL_ROOT)/lib
css_dir = $(etc_dir)/css
cfg_dir = $(etc_dir)/config_scripts

SUBDIRS = c_tools rust
INSTALLDIRS = $(GEMBS_INSTALL_ROOT) $(bin_dir) $(lib_dir) $(etc_dir) $(css_dir) $(cfg_dir)

.PHONY: subdirs $(SUBDIRS) installdirs all clean distclean texlive

all: $(TARGETS) gemBS

gemBS: gemBS_config.mk
	echo "#!/bin/sh" > $@
	echo 'LD_LIBRARY_PATH=$(lib_dir):$$LD_LIBRARY_PATH $(bin_dir)/gemBS $$@' >> $@
	chmod 755 $@
#	$(info **************************************************************************************************)
#	$(info copy shell script ${@} to a directory in your PATH (i.e., /usr/local/bin or ${HOME}/bin))
#	$(info **************************************************************************************************)

install: all installdirs
	cp rust/bin/* $(bin_dir)
	cp c_tools/bcftools/bcftools $(bin_dir)
	cp c_tools/samtools/samtools $(bin_dir)
	cp $(TMP_ROOT)/bin/bgzip $(bin_dir)
	cp c_tools/gem3-mapper/bin/gem-mapper $(bin_dir)
	cp c_tools/gem3-mapper/bin/gem-indexer $(bin_dir)
	cp -P $(TMP_ROOT)/lib/libhts* $(lib_dir)
	cp etc/css/style.css $(css_dir)
	cp etc/config_scripts/*.conf $(cfg_dir)
	strip $(bin_dir)/*
	cp gemBS $(INSTALL_PREFIX)/bin/

texlive: .texlive

clean:
	$(MAKE) -C rust clean
	$(MAKE) -C c_tools clean

distclean:
	$(MAKE) -C rust distclean
	$(MAKE) -C c_tools distclean
	rm -f .texlive texlive/gemBS_texlive.profile texlive/texlive_install.sh
	
subdirs: $(SUBDIRS)

$(SUBDIRS): 
	$(MAKE) -C $@

installdirs: $(INSTALLDIRS)

$(INSTALLDIRS):
	mkdir -p $@

$(bin_dir): $(GEMBS_INSTALL_ROOT)
$(etc_dir): $(GEMBS_INSTALL_ROOT)
$(lib_dir): $(GEMBS_INSTALL_ROOT)
$(css_dir): $(etc_dir)
$(cfg_dir): $(etc_dir)

texlive/gemBS_texlive.profile: texlive/gemBS_texlive.profile.in gemBS_config.mk
	sed 's+@GEMBS_INSTALL_ROOT+$(GEMBS_INSTALL_ROOT)+g;s+@INSTALL_PREFIX+$(INSTALL_PREFIX)+g' $< > $@

texlive/texlive_install.sh: texlive/texlive_install.sh.in gemBS_config.mk
	sed 's+@GEMBS_INSTALL_ROOT+$(GEMBS_INSTALL_ROOT)+g' $< > $@

.texlive: texlive/gemBS_texlive.profile texlive/texlive_install.sh
	cd texlive && sh texlive_install.sh && touch .texlive
